spring:
  application:
    name: customer

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/insurance_db
    username: db_user
    password: secret4321!!

server:
  port: 8081
